### ISSUE TITLE
Config exists in root project

### ISSUE THREAD

**Issue by rdzar** [DualDev/node-transip#14]
If you've included this lib into your project (e.g. dd-node-qq) and use `config/data.js` it will crash on `Module not found` with NodeJS v5.3.0 and up.

```
module.js:341
    throw err;
    ^

Error: Cannot find module './config/data.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

While `./config/data.js` exists in the cwd, but it seems to include within the TransIP lib or something. But I also wonder why not remove this anyway? Supplying the token+key trough the main instance would be nicer.

It may just be me, but I can't really see why it's doing that.

**Comment by DeviaVir** [comment]
https://github.com/DeviaVir/node-transip/commit/864bbf8319039cdcd12870741f6b348a46e177e4 should fix that, will do some tests

**Comment by DeviaVir** [comment]
Just pushed 0.0.5 that should fix this issue:
https://www.npmjs.com/package/transip
