### ISSUE TITLE
Unhandled rejection Error: 204

### ISSUE THREAD

**Issue by DenLanden** [DualDev/node-transip#17]
Hello,

I got a problem using the node-transip.
I can get data from TransIP.

But most of the time i want to send data i get the following error.

Unhandled rejection Error: 204: Invalid API signature, signature does not match the request.

Maybe you can point me in the right direction.

Have been trying all kinda things but keep getting the same error.

The function i am trying to use now is the : setDnsEntries.

```
var domain = 'domain.nl';

var item = [ { name: '*', expire: 86400, type: 'CNAME', content: '@' },
     { name: '@', expire: 86400, type: 'A', content: '123.456.789.123' },
     { name: '@', expire: 86400, type: 'MX', content: '10 @' },
     { name: 'ftp', expire: 86400, type: 'CNAME', content: '@' },
     { name: 'mail', expire: 86400, type: 'CNAME', content: '@' },
     { name: 'www', expire: 86400, type: 'CNAME', content: '@' } ] 

transip.domainService.setDnsEntries(domain, {'item':item}).then(function(response) {


});
```

Hope you can help me becouse i can't figure out what i am doing wrong.

With friendly regards,

**Comment by DeviaVir** [comment]
Hi @DenLanden!

How are you invoking `transip`? At a first glance, your code looks fine. Did you try something like this already?

```
var domain = 'domain.nl';

var item = [ { name: '*', expire: 86400, type: 'CNAME', content: '@' } ] 

transip.domainService.setDnsEntries(domain, {'item':item}).then(function(response) {


});
```

**Comment by DenLanden** [comment]
I already tried it with one record, same result.

I tried to invoke the transip two ways.

1st:
`
require('fs').readFile(privateKey, 'utf8', function(err, key){

```
    var TransIP         = require('transip');

    transip       = new TransIP(username, key);    
```

});
`
here i used a file with the privatekey in it.

The second way i tried it is like in the config sample file.

**Comment by rdzar** [comment]
Did you check the key and how you load it into JS?

**Comment by DeviaVir** [comment]
Perhaps it would help to try and pinpoint if the certificate key is the problem, or if the integration of `setDnsEntries` is somehow borked.

Could you try running this, and seeing if you get a certificate mismatch as well? If so, it is definitely the API key that is being placed wrong (did you notice the `\n` at the end of each line in the example config?)

```
transipInstance.domainService.getDomainNames().then(function(domains) {
  // Returns array of domain names
});
```

**Comment by DenLanden** [comment]
When i use that function i get a nice array of all the domains that are in my account.
I am also able to do getInfo that is how i get the dnsEntries at first.

And i saw the \n on the end of every line.

**Comment by DeviaVir** [comment]
That definitely points to `SetDnsEntries` as doing something silly.

Could you test one more thing? I'm wondering if the TransIP API is simply denying the change because of errors. What happens if you try this?

```
transipInstance.domainService.setDnsEntries(domain, {
  'item': [{
    'name': 'www',
    'expire': 10800,
    'type': 'A',
    'content': '123.456.789.123'
  }]
}).then(function(response) {
  // Returns response
  // boolean
})
```

**Comment by DenLanden** [comment]
That seems to work.
Getting a true

**Comment by DeviaVir** [comment]
@DenLanden That makes me think using `@` as `content` or `name` is not something the transip API particularly likes (or I'm not encoding it exactly how they'd like), if you keep building it out from here, adding back `@`'s as you go, at some point it will break- that's when you know that character is not allowed.

**Comment by DenLanden** [comment]
i don't know what happened but after first testing it line for line.
Now when i post it just the way i used to do, it works.

Not getting the error anymore.

**Comment by DeviaVir** [comment]
welcome in the magical realm of the transip api!

**Comment by DenLanden** [comment]
Sorry shouted to fast found the problem.
As soon when there is a wildcard in the name the error appears.

**Comment by DeviaVir** [comment]
Try to set the exact same records in the TransIP Control Panel, and see if you get an error when you try to do so.

**Comment by DenLanden** [comment]
They are the same records i get from TransIP. And when i try to save them at the Control Panel there is no problem. 

Even when i add a wilcard record it is wokring from the control panel

**Comment by DenLanden** [comment]
Logged every step the script makes towards sending it to TransIP.
The wildcard seems to stay the same. I only can't decode the string it sends.

**Comment by DeviaVir** [comment]
I think the character needs to be encoded to `"&#42;"` otherwise the XML might simply break. Re-opening this issue to see if I can solve it _the right way_

**Comment by DenLanden** [comment]
Yeah i see now the the "*" is not encoded right in urlencodeParameters thats how it looks like to me

`This is the "@" [name]=%40&1`
`This is the "*" [name]=*&1`

**Comment by DenLanden** [comment]
Found a quick fix.

in the utils.js i changed the function urlencode to:

```
exports.urlencode = function urlencode(string) {
    return encodeURIComponent(string).replace(/\*/g, '%2A');
};
```

**Comment by DeviaVir** [comment]
@DenLanden Sweet! Do you have any problems with `%` as well?

**Comment by DenLanden** [comment]
Don't have any domains with a % in the record it think that is not even allowed by TransIP

**Comment by DeviaVir** [comment]
Derp, I got confused, nevermind. Will add that piece of code! Thanks for finding that out.

**Comment by DenLanden** [comment]
No problem. Thank you for pointing me in the right direction.

**Comment by DeviaVir** [comment]
@DenLanden You can now upgrade your package.json to transip `0.0.6` and it should have your fix in the package!

**Comment by DenLanden** [comment]
@DeviaVir Thanks i will do that. Are you planning on doing the other TransIP functions to?
Like WebhostingService etc.
Becouse that is what i was busy with before this happened.

**Comment by DeviaVir** [comment]
@DenLanden Haven't had a need for those functions yet, which is why they have not yet been implemented sooner since the release.
But I'm open for PR's or might start working on it myself just to make sure this library is offering everything.
